language: python
cache:
  pip: true
  directories:
  # - datasets
before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
install:
    - pip install -e .[test] # install package + test dependencies
script:
    - pytest --cov=flights_time_series_dataset # run tests
after_success:
  - codecov # submit coverage 
